spring:
  cloud:
    stream:
      bindings:
        input:
          destination: my-topic # 消费的主题名称
          group: my-consumer-group # 消费者组名称
          content-type: application/json # 消息内容类型（例如JSON）
        output:
          destination: my-topic # 发送的主题名称
          group: my-producer-group # 发送的主题名称
          content-type: application/json

      rocketmq:
        binder:
          name-server: 127.0.0.1:9876 # RocketMQ NameServer 地址，确保是可用的
          producer-group: my-producer-group # 生产者组名称
          consumer-group: my-consumer-group # 消费者组名称
          instance-name: my-instance # 可选：RocketMQ实例名称
          group: my-group

      default:
        content-type: application/json # 默认的消息类型
