server:
  port: 8080
  servlet:
    context-path: /spring-mvc

spring:
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: [classpath:/mine/]
